"""add hidden in ChatVisibility

Revision ID: 10101e5b3c00
Revises: 9dba704415a8
Create Date: 2026-05-18 16:03:27.922517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10101e5b3c00'
down_revision = '9dba704415a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_visibility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_visibility', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
