"""empty message

Revision ID: 6a649f6d8264
Revises: ffc9e2da55fb
Create Date: 2026-05-09 16:58:42.128630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a649f6d8264'
down_revision = 'ffc9e2da55fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshots_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('screenshots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshots', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('screenshots_link')

    # ### end Alembic commands ###
