"""empty message

Revision ID: 7afa60389aea
Revises: 8e29b94fbec1
Create Date: 2026-05-08 23:42:51.938539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afa60389aea'
down_revision = '8e29b94fbec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint("check_status", type_ = "unique")
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('status')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motto', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('roles', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('project_idea', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('leader_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key("fk_leader_id_user_id", 'user', ['leader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint("fk_leader_id_user_id", type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('leader_id')
        batch_op.drop_column('project_idea')
        batch_op.drop_column('roles')
        batch_op.drop_column('motto')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('cancelled')

    op.create_table('_alembic_tmp_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cancelled', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('organizer_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
