"""empty message

Revision ID: 9dba704415a8
Revises: 4292d2423628
Create Date: 2026-05-18 11:13:27.244997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dba704415a8'
down_revision = '4292d2423628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_receiver')
        batch_op.drop_column('deleted_by_sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_sender', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_receiver', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
