"""Updated event table 2

Revision ID: add35fdbea6a
Revises: 8a5c84b7ef70
Create Date: 2026-05-03 22:18:22.252328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add35fdbea6a'
down_revision = '8a5c84b7ef70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('cancelled')

    # ### end Alembic commands ###
