"""Fixing migration sync

Revision ID: bd558532edfd
Revises: 3907273beaea
Create Date: 2026-04-27 20:38:38.687589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd558532edfd'
down_revision = '3907273beaea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_receiver')
        batch_op.drop_column('deleted_by_sender')

    # ### end Alembic commands ###
