"""empty message

Revision ID: e4533db58a9d
Revises: 6eefb7a05eae
Create Date: 2026-04-21 22:24:35.477425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4533db58a9d'
down_revision = '6eefb7a05eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_dashboard_id', 'dashboard', ['dashboard_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_dashboard_id', type_='foreignkey')
        batch_op.drop_column('dashboard_id')

    # ### end Alembic commands ###
