"""initial migration with last_seen

Revision ID: f2bcd95194e4
Revises: 
Create Date: 2026-05-05 02:02:59.337616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bcd95194e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_receiver')
        batch_op.drop_column('deleted_by_sender')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
