"""empty message

Revision ID: ffc9e2da55fb
Revises: 99fdad6bf358
Create Date: 2026-05-09 16:56:03.209866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc9e2da55fb'
down_revision = '99fdad6bf358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('screenshots',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('screenshots',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
